# .github/workflows/auto-merge-dependabot-pr.yml
name: Auto-merge Dependabot PR
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}

    steps:
      - name: Approve Dependabot PR
        run: gh pr review --approve $PR_URL

      - name: Auto-merge Dependabot PR
        if: contains(github.event.pull_request.title, 'deps-dev')
        run: gh pr merge --auto --merge $PR_URL 